adding new project for new user manager
celements/celements-features pull request #20
Opened 2023-06-22 13:17 UTC by cbspichler

https://synjira.atlassian.net/browse/CELDEV-1108

2023-06-28 12:13 UTC, msladek requested changes

2023-06-28 12:13 UTC, msladek commented on celements-user-manager/component/pom.xml
> +        <dependency>
```suggestion
    <dependency>
```

2023-06-28 12:13 UTC, msladek commented on celements-user-manager/web-module/src/main/webapp/WEB-INF/remember_me.txt
> +needed for building, as long as there is no other content in WEB-INF
replace with `web.xml`

2023-07-04 14:37 UTC, msladek requested changes

2023-07-04 14:37 UTC, msladek commented on celements-user-manager/web-module/src/main/webapp/WEB-INF/web.xml
> +</web-app>
last line misses EOL

2023-07-06 13:56 UTC, msladek approved these changes

2023-07-07 10:07 UTC, fpichler approved these changes

2023-07-07 12:55 UTC, merged