CELDEV-1223 - Save action of new User Manager does not work
celements/celements-features pull request #44
Opened 2024-05-07 15:50 UTC by cbspichler

https://synjira.atlassian.net/browse/CELDEV-1223

2024-05-07 22:51 UTC, fpichler submitted a review, later dismissed

2024-05-08 12:26 UTC, msladek requested changes

2024-05-08 12:26 UTC, msladek commented on celements-user-manager/web-module/.gitignore
> +/.apt_generated_tests/
please add the exclude on git root level once for all subdirs

2024-05-09 05:34 UTC, fpichler approved these changes

2024-05-10 08:15 UTC, msladek approved these changes

2024-05-10 20:23 UTC, merged