CELDEV-1222 - Search Query for New User Manager is wrong
celements/celements-features pull request #45
Opened 2024-05-07 16:07 UTC by cbspichler

https://synjira.atlassian.net/browse/CELDEV-1222

2024-05-07 22:44 UTC, fpichler requested changes

2024-05-07 22:44 UTC, fpichler commented on celements-user-manager/web-module/src/main/webapp/templates/celMacros/userAdmin/searchQuery.vm
> +wiki: $context.database AND type:wikipage AND Celements2.PageType.page_type:User AND space:XWiki
```suggestion
wiki:${context.database} AND type:wikipage AND Celements2.PageType.page_type:User AND space:XWiki
```

2024-05-12 19:58 UTC, msladek approved these changes

2024-05-12 20:12 UTC, fpichler approved these changes

2024-05-12 22:46 UTC, merged