CELDEV-1177 - User save validation (server-side)
celements/celements-features pull request #46
Opened 2024-07-08 12:34 UTC by cbspichler

https://synjira.atlassian.net/browse/CELDEV-1177

2024-07-09 08:13 UTC, msladek requested changes

2024-07-09 08:13 UTC, msladek commented on celements-user-manager/component/src/main/java/com/celements/auth/user/CelementsUserService.java
> +
```suggestion
```
please also remove all other empty lines within non-test methods in this PR.

2024-07-09 08:13 UTC, msladek commented on celements-user-manager/component/src/main/java/com/celements/auth/user/validation/XWikiUsersValidationRule.java
> +  private IRightsAccessFacadeRole rightsAccess;
```suggestion
  private final IMailSenderRole mailSenderService;
  private final UserService userService;
  private final IRightsAccessFacadeRole rightsAccess;
```
injected beans should generally be defined as `final` for clarity.

2024-07-09 08:13 UTC, msladek commented on celements-user-manager/component/src/main/java/com/celements/auth/user/validation/XWikiUsersValidationRule.java
> +    return validationResults.collect(Collectors.toList());
the local `validationResults` var is not needed:
```suggestion
    return getEmailParam(params)
        .map(this::validate)
        .orElse(Stream.empty()))
        .collect(Collectors.toList());
```

2024-07-09 08:13 UTC, msladek commented on celements-user-manager/component/src/main/java/com/celements/auth/user/validation/XWikiUsersValidationRule.java
> +            .equals(new RefBuilder().space("XWiki").doc("XWikiUsers").build(ClassReference.class)))
use static ClassReference already defined in `XWikiUsersClass`

2024-07-09 08:13 UTC, msladek commented on celements-user-manager/component/src/main/java/com/celements/auth/user/validation/XWikiUsersValidationRule.java
> +    return validationResults;
i think this method is hard to read, primarily because of the many `Stream.concat` statements.
It could likely be simplified by defining the internal `validationResults` as list and use `ifPresent`:
```
checkX(...).ifPresent(validationResults::add);
checkY(...).ifPresent(validationResults::add);
checkZ(...).ifPresent(validationResults::add);
return validationResults.stream();
```

2024-07-09 08:13 UTC, msladek commented on celements-user-manager/component/src/main/java/com/celements/auth/user/validation/XWikiUsersValidationRule.java
> +        .of(new ValidationResult(ValidationType.ERROR, null, "cel_useradmin_emailInvalid"));
if you want it to be more "idiomatic" for the Optional/Stream-API you could use `Optional.ofNullable(email)` with `filter` and `map`, but it's not a must.

same applies for `checkUniqueEmail` and `checkRegisterAccessRights` and `checkXWikiSpace`.

2024-07-15 07:29 UTC, msladek requested changes

2024-07-15 07:29 UTC, msladek commented on celements-user-manager/component/src/main/java/com/celements/auth/user/validation/XWikiUsersValidationRule.java
> +  private final IRightsAccessFacadeRole rightsAccess;
list class members after constants

2024-07-15 07:29 UTC, msladek commented on celements-user-manager/component/src/main/java/com/celements/auth/user/validation/XWikiUsersValidationRule.java
> +      IRightsAccessFacadeRole rightsAccess) {
```suggestion
      IMailSenderRole mailSenderService,
      UserService userService,
      IRightsAccessFacadeRole rightsAccess) {
```

2024-07-15 07:29 UTC, msladek commented on celements-user-manager/component/src/main/java/com/celements/auth/user/validation/XWikiUsersValidationRule.java
> +    if (emailParam.get().getValues().size() > 1) {
shouldn't this check be part of `hasSeveralEmailParams`?

2024-07-15 07:30 UTC, msladek commented
this is really well structured and readable code. thank you!

2024-07-15 12:45 UTC, cbspichler commented on celements-user-manager/component/src/main/java/com/celements/auth/user/validation/XWikiUsersValidationRule.java
> +    if (emailParam.get().getValues().size() > 1) {
Yes and no. ;-)
The missing email check needs a more specific message than just "invalid request". You can get this message through normal use of our editor. The second check might be more suitable in `hasSeveralEmailParams` but might throw exceptions without the missing email check. I do not want to tear them apart and I do not want to move both.

2024-07-15 12:51 UTC, msladek commented on celements-user-manager/component/src/main/java/com/celements/auth/user/validation/XWikiUsersValidationRule.java
> +    if (emailParam.get().getValues().size() > 1) {
I wasn't commenting the missing email check but specifically line 116, the check for multiple email values within one param. the lines above are just displayed by github for context.

I'm not following your concern, what execption do you mean? Couldn't you just do a
`getEmailParams(params).flatMap(p -> p.getValues()).count() > 1` check in `hasSeveralEmailParams`?

2024-07-15 14:05 UTC, msladek approved these changes

2024-07-15 14:15 UTC, merged